server:
  port: 8080
  servlet:
    context-path: /karental

application:
  security:
    jwt:
      access-token-cookie-name: karental-jwt
      refresh-token-cookie-name: karental-jwt-refresh
      #TODO: cái key này phải bỏ vào biến môi trường
      secret-key: ${JWT_SECRET_KEY}
      access-token-expiration: 86400000 #milisecond ~ 24 hours
      refresh-token-expiration: 604800000 #~7days

      #FOR TEST
#      access-token-expiration: 15000 #milisecond ~ 15s
#      refresh-token-expiration: 60000 #~1 minute

spring:
  application:
    name: karental
  datasource:
    url: "jdbc:mysql://localhost:3306/karental"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
cloud:
  aws:
    region:
      static: ap-southeast-1
    s3:
      buckets:
        name: karental
