server:
  port: 8080
  servlet:
    context-path: /karental

application:
  security:
    jwt:
      access-token-secret-key: ${JWT_ACCESS_SECRET_KEY}
      access-token-cookie-name: karental-jwt
      refresh-token-cookie-name: karental-jwt-refresh
      refresh-token-secret-key: ${JWT_REFRESH_SECRET_KEY}
      access-token-expiration: 3600000  #milisecond ~ 1 hours
      refresh-token-expiration: 86400000 #~1day
    public-endpoints:
      "/user/register,
      /user/check-unique-email,
      /user/resend-verify-email/**,
      /user/verify-email/**,
      /auth/**"
##      FOR TEST
#      access-token-expiration: 15000 #milisecond ~ 15s
#      refresh-token-expiration: 60000 #~1 minute

spring:
  application:
    name: karental
  datasource:
    url: jdbc:mysql://localhost:3306/karental
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAILTRAP_USERNAME}
    password: ${MAILTRAP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 6000
      database: 0

springdoc:
  swagger-ui:
    enabled: false
cloud:
  aws:
    region:
      static: ap-southeast-1
    s3:
      buckets:
        name: karental
front-end:
  domain-name: http://localhost:3000

payment:
  vnpay:
    tmn-code: ${TMN_CODE}
    secret-key: ${VNPAY_SECRET_KEY}
    init-payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: http://localhost:3000/my-wallet
    timeout: 2 # in minutes
