server:
  port: 8080
  servlet:
    context-path: /karental

spring:
  application:
    name: karental
  datasource:
    url: "jdbc:mysql://localhost:3306/karental"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

