server:
  port: 8080
  servlet:
    context-path: /karental

application:
  security:
    jwt:
      access-token-secret-key: ${JWT_ACCESS_SECRET_KEY:k6jc9lypr7vm7api0r9v7y2k1c37hr4hneeqlkm93lr355hran2nhpwhqv8pnuqvbq29a2tfsfcf9ebikbn0arzllmhjrp7hp4z3emfxqyozg2hrozcyhmxaa1wulr7s}
      access-token-cookie-name: karental-jwt
      refresh-token-cookie-name: karental-jwt-refresh
      #TODO: cái key này phải bỏ vào biến môi trường
      refresh-token-secret-key: ${JWT_REFRESH_SECRET_KEY:4iyhevpv5jvq34g7ugtzw1dyuegkq683gctxs9xzye9ufwee6y7w6b0pwxc00na4te7s4w0e3rw1tu5756ws3pi58unz9chg4f04bh9bw9kyfftieupth6x3gy80saus}
      access-token-expiration: 3600000  #milisecond ~ 1 hours
      refresh-token-expiration: 86400000 #~1day

##      FOR TEST
#      access-token-expiration: 15000 #milisecond ~ 15s
#      refresh-token-expiration: 60000 #~1 minute

spring:
  application:
    name: karental
  datasource:
    url: "jdbc:mysql://localhost:3306/karental"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
cloud:
  aws:
    region:
      static: ap-southeast-1
    s3:
      buckets:
        name: karental
