name: karental-application

services:
  redis:
    image: redis:7.4.2
    container_name: redis7
    restart: unless-stopped
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf  # Mount file config
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]  # Run redis with custom config
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - internal

  app:
    image: huyendieu8304/karental:1.0
    container_name: karental-springboot-app
    restart: unless-stopped
    #    ports:
    #      - "8080:8080"
    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKETNAME: ${AWS_S3_BUCKETNAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DB_URL: ${DB_URL}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      JWT_ACCESS_SECRET_KEY: ${JWT_ACCESS_SECRET_KEY}
      JWT_REFRESH_SECRET_KEY: ${JWT_REFRESH_SECRET_KEY}
      JWT-CSRF-SECRET-KEY: ${JWT-CSRF-SECRET-KEY}
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      TMN_CODE: ${TMN_CODE}
      VNPAY_SECRET_KEY: ${VNPAY_SECRET_KEY}
      APPLICATION_EMAIL: ${APPLICATION_EMAIL}
      FE_BASE_URL: ${FE_BASE_URL}
      VNPAY_RETURN_URL: ${VNPAY_RETURN_URL}
      DOMAIN_NAME: ${DOMAIN_NAME}
    depends_on:
      - redis
    networks:
    - internal

  caddy:
    image: caddy:2.9.1
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - internal
    depends_on:
      - app
volumes:
  redis_data:
  caddy_data:
  caddy_config:
networks:
  internal:
    driver: bridge
