name: karental-application

services:
  redis:
    image: redis:7.4.2
    container_name: redis7
    restart: unless-stopped
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf  # Mount file config
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]  # Run redis with custom config
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - internal

  app:
    image: huyendieu8304/karental:1.0
    container_name: karental-springboot-app
    #    ports:
    #      - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DB_URL: ${DB_URL}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      JWT_ACCESS_SECRET_KEY: ${JWT_ACCESS_SECRET_KEY}
      JWT_REFRESH_SECRET_KEY: ${JWT_REFRESH_SECRET_KEY}
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      TMN_CODE: ${TMN_CODE}
      VNPAY_SECRET_KEY: ${VNPAY_SECRET_KEY}
      APPLICATION_EMAIL: ${APPLICATION_EMAIL}
      FE_BASE_URL: ${FE_BASE_URL}
      VNPAY_RETURN_URL: ${VNPAY_RETURN_URL}
      DOMAIN_NAME: ${DOMAIN_NAME}
    depends_on:
      - redis
    networks:
    - internal
    restart: unless-stopped

  nginx:
    image: nginx:1.27.4
    container_name: nginx
    ports:
      - "443:443" # Open HTTPS
      - "80:80"   # Just open it for Certbot validation
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/certs:/etc/letsencrypt
    networks:
      - internal
    restart: unless-stopped

  certbot:
    image: certbot/certbot:v3.2.0
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/certs:/etc/letsencrypt

    restart: unless-stopped
    entrypoint: /bin/sh -c "certonly --webroot --webroot-path /var/www/certbot --email huyendieu8304@gmail.com -d karental.api.okne.site --agree-tos --no-eff-email --force-renewal && cp -r /etc/letsencrypt /certs"

volumes:
  redis_data:

networks:
  internal:
    driver: bridge
